# Generated by Django 3.2.4 on 2024-10-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_type', models.CharField(choices=[('Doctor', 'Doctor'), ('Hospital', 'Hospital'), ('Lab', 'Lab')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('compliment_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=10, unique=True)),
                ('patientname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True)),
                ('age', models.IntegerField()),
                ('age_type', models.CharField(max_length=10)),
                ('sample_collector', models.CharField(max_length=100)),
                ('organisation', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('lab_id', models.CharField(blank=True, max_length=50)),
                ('refby', models.CharField(blank=True, max_length=100)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('B2B', models.CharField(blank=True, max_length=100)),
                ('home_collection', models.CharField(blank=True, max_length=100)),
                ('testname', models.JSONField(max_length=100)),
                ('totalAmount', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SampleCollector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(max_length=100, unique=True)),
                ('specimen_type', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
                ('reference_range', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=10)),
                ('patientname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('date', models.CharField(max_length=100)),
                ('testdetails', models.JSONField()),
            ],
        ),
    ]
