# Generated by Django 3.2.4 on 2024-10-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_organisation_patient_samplecollector_test_testvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testvalue',
            name='date',
            field=models.DateField(),
        ),
    ]
